# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper.rb"` to ensure that it is only
# loaded once.

require 'rails/all'
require 'active_record'
require 'combustion'
require 'rspec/rails'

Combustion.initialize!

$LOAD_PATH << File.expand_path('../../app/models', __FILE__)
$LOAD_PATH << File.expand_path('../../app/controllers', __FILE__)

# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
end
